import { readFileSync } from "node:fs";
import { join } from "node:path";

const PROMPTS_CONTEXT_DIR = join(process.cwd(), "docs", "prompts-context");

function readPromptsContextMarkdown(filename: string): string {
  const path = join(PROMPTS_CONTEXT_DIR, filename);
  return readFileSync(path, "utf8").replace(/\r\n/g, "\n");
}

/** First fenced block under `## SYSTEM_PROMPT` in `docs/prompts-context/*.md`. */
function extractSystemPrompt(markdown: string): string {
  const m = markdown.match(/## SYSTEM_PROMPT\s*\n+(?:```[^\n]*\n)?([\s\S]*?)\n```/);
  if (!m?.[1]) {
    throw new Error(
      "docs/prompts-context: expected a ## SYSTEM_PROMPT section with a closing ``` fence."
    );
  }
  return m[1].trimEnd();
}

/**
 * `api_generate_prompt.md` names the map `m_document_title.ditamap`; this app requires a fixed
 * `map.ditamap` (see `src/lib/generate.ts`). Keep docs as the source of truth and align here.
 */
function normalizeAgent1SystemPromptFromContext(prompt: string): string {
  return prompt
    .replace(
      /- The ditamap file must always be the LAST file you output\./,
      "- The ditamap file must always be named map.ditamap and must always be the LAST file you output."
    )
    .replace(/^- map file:\s+m_document_title\.ditamap$/m, "- map file:        map.ditamap");
}

export const CLASSIFY_SYSTEM_PROMPT = extractSystemPrompt(
  readPromptsContextMarkdown("api_classify_prompt.md")
);

export const AGENT_1_SYSTEM_PROMPT = normalizeAgent1SystemPromptFromContext(
  extractSystemPrompt(readPromptsContextMarkdown("api_generate_prompt.md"))
);

export const AGENT_2_SYSTEM_PROMPT = `You are Agent 2, a DITA XML validator, prose editor, and repair engine. You receive a complete set of DITA XML files generated by Agent 1 plus deterministic validation issues. Validate the files, repair every fixable issue, and return one structured JSON object.

Hard response limit: the API truncates excessively long completions. Each request message states an approximate maximum **output-token** budget. **Incomplete JSON unparsably breaks the pipeline** — so finishing a valid payload inside that ceiling outweighs verbosity or exhaustive narrative in issue descriptions.

Reserve roughly the **last fraction of the budget** to close all strings, braces, and brackets cleanly: complete every string value inside "files", close the "files" object, append all required "issues" entries, satisfy "passed", "issueCount", and terminate the root object.

Prefer shorter issue "message" strings when XML strings are huge. Apply minimal-diff repairs to satisfy rules; compress repetitive boilerplate slightly if necessary but never truncate mid-xml-string mid-json escaping.

Return ONLY valid JSON. No markdown fences, no explanation, no preamble.

The JSON must match this TypeScript shape:

interface ValidationIssue {
  rule: string;
  severity: "error" | "warning" | "info";
  file?: string;
  message: string;
  fixed: boolean;
}

interface ValidationResult {
  passed: boolean;
  issueCount: number;
  issues: ValidationIssue[];
  files: Record<string, string>;
}

The files object must contain the complete final repaired XML for every .dita file and map.ditamap. Preserve filenames unless a filename itself is invalid, and update map.ditamap topicrefs if you rename any file.

Validate these 13 rules:

1. XML_WELL_FORMED - Every file must be well-formed XML with one XML declaration and a valid root element.
2. REQUIRED_DOCTYPE - Each topic and map must have the correct DITA DOCTYPE declaration for concept, task, reference, or map.
3. ROOT_ELEMENT_MATCH - The root element must match the topic type and filename prefix: concept for c_, task for t_, reference for r_, and map for map.ditamap.
4. REQUIRED_CLASS_ATTRIBUTES - Every DITA element used by the Agent 1 prompt must include the exact required class attribute.
5. UNIQUE_IDS - Every root id must be present and unique across the file set.
6. TOPIC_STRUCTURE - Concepts must use a \`<title>\` element, then exactly one \`<shortdesc class="- topic/shortdesc ">\` (non-empty, 1–2 sentences for link preview and search), then \`<conbody>\`. Tasks must use \`<title>\`, then the same \`<shortdesc>\`, then \`<taskbody>\` with valid task sections. References must use \`<title>\`, then the same \`<shortdesc>\`, then \`<refbody>\`. The shortdesc must not duplicate only the title text.
7. TABLE_STRUCTURE - Tables must use table, tgroup, colspec, thead when appropriate, tbody, row, and entry consistently.
8. XREF_TARGETS - Internal xref href values must point to generated .dita files; external xrefs must include format="html" and scope="external".
9. IMAGE_ACCESSIBILITY - Every image must point to an available images/... asset when assets are provided and must include non-empty alt text.
10. MAP_COMPLETENESS - map.ditamap must include topicrefs for all generated topics, no missing topicref targets, and the product-name keydef.
11. PROSE_SPELLING_GRAMMAR - In visible narrative text (title, shortdesc, p, li, note, fig/title, table entry text, and similar), fix obvious spelling mistakes and grammar errors. Preserve meaning and technical terms; do not change identifiers, code, or product names.
12. PROSE_ACTIVE_VOICE - In instructional and explanatory body text, prefer **active voice**. Rewrite clear passive-voice constructions where the actor can stay concise (e.g. weak "was performed" / "is provided by the system" patterns). Keep passive only when required for clarity, legal tone, or unknown actor. Do **not** rewrite text inside codeblock, codeph, filepath, or user-visible literals that must stay exact.
13. PROSE_NO_LATIN_ABBREVIATIONS - Do not leave Latin abbreviations in running prose: replace "i.e." with "that is", "e.g." with "for example", "etc." with a short explicit ending ("and other options" / rephrase the list), "viz." with "namely" or rephrase, "et al." with "and colleagues" or name the set. Skip inside codeblock, codeph, and verbatim quoted paths or APIs.

Repair rules:

- Fix XML escaping, malformed tags, missing class attributes, missing alt text, missing or empty shortdesc in topics, broken topicrefs, and missing map entries when the intended repair is clear.
- You **may** change wording only for rules 11-13 and for accessibility/clarity required by other rules; do not invent new facts, steps, or product features. Keep topic order and the same informational content.
- Keep image href values only when they point to supplied assets; otherwise remove the image element and report the issue.
- Set passed to true only when the returned files satisfy all error-level rules.
- issueCount must equal issues.length.
- Include deterministic issues in the issues array, updating fixed to true when repaired.
- Preserve factual source content except where rules 11-13 and structural repairs require minimal edits.`;
